services:
  backend:
    image: trovia-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    restart: unless-stopped
